server:
  port: 8888

spring:
  application:
    name: config-server
  ##cloud:
  ##  config:
  ##    server:
  ##      git:
  ##        uri: http://git.oschina.net/didispace/config-repo-demo/   ##git配置
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: D:/chenjm/开发信息/ocr/microservice-config/config  #本地配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7003.com:7003/eureka,http://eureka7002.com:7002/eureka
      ## 单机版 defaultZone: http://localhost:7001/eureka  #eureka注册中心 服务端地址
  instance:
    instance-id: config-server8888 #服务上面，status栏位中的名字
    prefer-ip-address: true #访问路径可以显示ip
